name: 'Vite Pages'
description: 'This action builds and deploys a static site to GitHub Pages using pnpm and Vite.'
author: 'GrafLearnt'
inputs:
  token:
    description: 'GitHub token used to authenticate.'
    required: true
  branch:
    description: 'The branch to deploy from (default: main).'
    required: false
    default: 'main'
  viteBuildCommand:
    description: 'The command to build your site using Vite.'
    required: false
    default: 'pnpm vite build'
  distFolder:
    description: 'The folder that contains the static site to deploy.'
    required: false
    default: 'dist'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build site
      run: ${{ inputs.viteBuildCommand }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.distFolder }}

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ inputs.token }}

permissions:
  contents: read
  pages: write
  id-token: write

branding:
  icon: 'upload-cloud'
  color: 'blue'
